### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by KingDuckZ** [gentoo/dlang#13]
I've been using gcc 4.8 for a while now and I haven't had any problems building anything on the system. I'd like to update to the latest 4.8 (currently 4.8.4) but there is no ebuild for it on this overlay, so updating would make me lose gdc.
The same goes for gcc 4.9, if possible.

**Comment by mleise** [comment]
Thanks, I'll come back to this.

**Comment by mleise** [comment]
I'm creating an ebuild for gcc 4.8.4 with the 2.066.1 front-end. Since for proper dependency management (for packages requiring a specific D front-end version) I need to match gcc versions with dlang versions. gcc 4.9.2 would be the version that ships with 2.067 once it is officially released. In fact the gdc project itself only tags releases after then next dmd version is available rendering the previous version final. So their latest tag is still 2.065.
I'm not doing the same, but that means that when a possible 2.067.1 is released I usually do not have a corresponding gcc-4.8.4-r1 or gcc-4.8.5 available to upgrade to. Instead I just change the existing ebuilds to point to a new GitHub commit of gdc. This change is not seen by portage and one has to manually reinstall gcc if this happens.

**Comment by mleise** [comment]
An ebuild for 4.9 will come when GDC is released with 2.068 front-end!
