### ISSUE TITLE
Add dmd-9999

### ISSUE THREAD

**Issue by Connor-GH** [gentoo/dlang#132]
I currently have a bug with my DMD that gets patched in 2.110.0-beta.1 but of course this is a beta and probably shouldn't have an official ebuild made for it. Is it possible that you could supply a 9999 build so that I can pull from git when needed? (my workflow also revolves around updating the compiler and using the latest features)

**Comment by the-horo** [comment]
I've thought about the 9999 variants for dmd and ldc2 but I skipped it mainly because it didn't sound like something very important. I can look into it but it may take me a while since I haven't thought of a full solution yet and I may encounter difficulties.

If you really want a newer version soon I have nothing against adding beta ebuilds for dmd and ldc2. There already are  ebuild for beta releases of other projects. True, I've done this mainly because those projects don't have regular releases cycles so I don't know when a new stable version will be released, but dmd skipping scheduled releases is pretty much the same thing. The eclass is supposed to work with beta versions https://github.com/gentoo/dlang/blob/68dacc91c61f921f1561db7bd7be340ef203beaf/eclass/dmd-r1.eclass#L71-L72 and bumping it should be as simple as copying the `.ebuild` file so I would be able to do it faster.

Since I'm the current maintainer of these packages I suppose my opinion is the one that's to be followed in the overlay and, so long as the ebuild is un-keyworded and works and people use it I have nothing against adding it to this overlay.

**Comment by the-horo** [comment]
I've added dmd-2.110.0_beta1 to the tree. Be sure to `package.accept_keywords` it and use it but keep this issue open until I add the 9999 ebuild for it.

**Comment by Connor-GH** [comment]
The keywords are commented out. Any reason for this?

**Comment by the-horo** [comment]
Like you said, since it's a beta release it doesn't get the same amount of support as a normal release and, it terms of `KEYWORDS` this translates to being *less stable* then a normal release. Since normal releases have unstable keywords, one less than that is no keywords at all.
